title: PrintOnDemand License
description: License, Trademark info, and changelog
theme: just-the-docs
# logo: "your_logo_path"
# favicon_ico: "your_icon_path"

url: https://github.com/PrintOnDemand-Official/License

aux_links:
  Repository: https://github.com/PrintOnDemand-Official/License