title: PrintOnDemand License
description: License, Trademark info, and changelog
theme: just-the-docs
search_enabled: false
# logo: "your_logo_path"
# favicon_ico: "your_icon_path"

url: https://github.com/PrintOnDemand-Official/License

aux_links:
  Repository: https://github.com/PrintOnDemand-Official/License

# # Enable Just the Docs' navigation structure
# just_the_docs:
#   collections:
#     docs:
#       output: true
#   nav:
#     - title: "Overview"
#       url: "/docs/overview/"
#       children:
#         - title: "Intellectual Property"
#           url: "/docs/intellectual_property/"