title: PrintOnDemand License
description: License, Trademark info, and changelog
theme: just-the-docs
search_enabled: false
# logo: "your_logo_path"
# favicon_ico: "your_icon_path"

url: https://github.com/PrintOnDemand-Official/License

aux_links:
  "PintOnDemand on GitHub":
    - "//github.com/PrintOnDemand-Official"

color_scheme: dark

include:
  - assets